jobs:
  build:
    env:
      MAVEN_ARGS: -Dmaven.resolver.transport=wagon
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - continue-on-error: true
      name: Install dependencies
      run: 'brew install openssl

        brew install autoconf

        brew install automake

        brew install libtool

        brew install cmake

        '
    - continue-on-error: true
      name: build natives
      run: ./build.sh
name: Test PRs
on:
  repository_dispatch:
    types: trigger-ga___build.yml
