jobs:
  printInputs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - continue-on-error: true
      name: Install dependencies
      run: 'brew install autoconf automake pkg-config libtool cmake

        '
    - continue-on-error: true
      name: Build libhfscompressor natives
      run: 'cd compiler/libhfscompressor

        ./build.sh ${{ github.event.inputs.scriptArgs }}

        '
    - continue-on-error: true
      name: Push changes to the branch
      run: 'git checkout -b "${{ github.event.inputs.targetBranch }}"

        git add compiler/bin

        git commit -m "${{ github.event.inputs.commitMessage }}"

        git push --set-upstream origin "${{ github.event.inputs.targetBranch }}"'
name: Build libhfscompressor (MacOSX)
on:
  repository_dispatch:
    types: trigger-ga___native_libhfs_darwin.yml
