jobs:
  build:
    env:
      MAVEN_ARGS: -Dmaven.resolver.transport=wagon
      MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Install dependencies
      run: 'brew install openssl

        brew install autoconf

        brew install automake

        brew install libtool

        brew install cmake

        '
    - continue-on-error: true
      name: build natives
      run: ./build.sh
    - continue-on-error: true
      name: Maven deploy
      run: mvn clean deploy
    - continue-on-error: true
      name: Gradle plugin deploy
      run: cd plugins/gradle && ./gradlew clean build publish
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: eu-west-3
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    - continue-on-error: true
      name: Deploy idea plugin
      run: aws s3 sync ./plugins/idea/build/distributions/ s3://${{ secrets.AWS_BUCKET
        }}/snapshots/idea --acl public-read --follow-symlinks --delete
    - continue-on-error: true
      name: Deploy eclipse plugin
      run: aws s3 sync ./plugins/eclipse/update-site/target/repository/ s3://${{ secrets.AWS_BUCKET
        }}/snapshots/eclipse --acl public-read --follow-symlinks --delete
name: Build library and deploy snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
